import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Wrapper from "@/Wrapper/Wrapper";

export const metadata = {
  title: "TechConnect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body suppressHydrationWarning={true}>
        <Toaster />
        <Wrapper>
          <>
            <Navbar />
            <div className="min-h-[90vh]">{children}</div>
          </>
        </Wrapper>
        <Footer />
      </body>
    </html>
  );
}
